version: 2

jobs:
  toxify:
      docker:
        - image: python:3.6
      steps:
        - checkout
        - run: pip install tox && tox
        - run: pip install codecov && codecov

workflows:
  version: 2

  django-yearlessdate:
    jobs:
      - toxify