# Generated by Django 2.0.7 on 2018-08-01 11:11

from django.db import migrations, models
import djangoyearlessdate.helpers
import djangoyearlessdate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearlessDateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearless_date', djangoyearlessdate.models.YearlessDateField(max_length=4)),
                ('optional_yearless_date', djangoyearlessdate.models.YearlessDateField(blank=True, max_length=4, null=True)),
                ('yearless_date_with_default', djangoyearlessdate.models.YearlessDateField(default=djangoyearlessdate.helpers.YearlessDate(day=3, month=5), max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', djangoyearlessdate.models.YearField()),
            ],
        ),
    ]
